app:
  host: 0.0.0.0
  port: 9090

mongodb:
  uri: mongodb+srv://db_user:KMnpu5CSGuZ12gFb@jacdb.gin66tb.mongodb.net/?appName=jacdb&retryWrites=true&w=majority
  db_name: jacdb

rabbitmq:
  amqp_url: amqp://admin:admin123@localhost:5672/
  exchange: camera.frames
  #User & Vhost: bjoijfms
  #Password: 3sq1Ot7F5rIfdZ3xKXBJcJ7spLt0_QJz
  #Ports: 5672 (5671 for TLS)
  #Region	amazon-web-services::us-east-1
  #Cluster	possum.lmq.cloudamqp.com (DNS load balanced)
  #Hosts	possum-01.lmq.cloudamqp.com
  #(Availability Zone use1-az1)
  #Created at	2025-11-22 15:04 UTC+00:00

ingest:
  jpeg_quality: 80
  target_fps: 10
  reconnect_delay_seconds: 5
  thumbnail_width: 150
  thumbnail_height: 150

storage:
  base_path: ./recordings
  